// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0KpnR_fFaeG461KuYl4s0TYXPaUzHZQg',
    appId: '1:865509542559:web:8dc8458e4215aeccb4b0aa',
    messagingSenderId: '865509542559',
    projectId: 'push-noti-demo-8611a',
    authDomain: 'push-noti-demo-8611a.firebaseapp.com',
    storageBucket: 'push-noti-demo-8611a.appspot.com',
    measurementId: 'G-GKBK8W538D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6HFYHbnNABlq_jgwID5nAVOdJ1kqo8aw',
    appId: '1:865509542559:android:17bb40aeba9d8909b4b0aa',
    messagingSenderId: '865509542559',
    projectId: 'push-noti-demo-8611a',
    storageBucket: 'push-noti-demo-8611a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHG8ZqTRXWS-NzzTZKTbp_GGXK7dqYwUE',
    appId: '1:865509542559:ios:007ebec9aa3ee4b1b4b0aa',
    messagingSenderId: '865509542559',
    projectId: 'push-noti-demo-8611a',
    storageBucket: 'push-noti-demo-8611a.appspot.com',
    iosBundleId: 'com.example.flutterFcmPushNoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHG8ZqTRXWS-NzzTZKTbp_GGXK7dqYwUE',
    appId: '1:865509542559:ios:007ebec9aa3ee4b1b4b0aa',
    messagingSenderId: '865509542559',
    projectId: 'push-noti-demo-8611a',
    storageBucket: 'push-noti-demo-8611a.appspot.com',
    iosBundleId: 'com.example.flutterFcmPushNoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0KpnR_fFaeG461KuYl4s0TYXPaUzHZQg',
    appId: '1:865509542559:web:fef24f9a15aba9cab4b0aa',
    messagingSenderId: '865509542559',
    projectId: 'push-noti-demo-8611a',
    authDomain: 'push-noti-demo-8611a.firebaseapp.com',
    storageBucket: 'push-noti-demo-8611a.appspot.com',
    measurementId: 'G-W5D737DXEE',
  );
}
